//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAboutEverything.LocalizationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Movie_Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Movie_Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalAboutEverything.LocalizationResources.Movie_Index", typeof(Movie_Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of reviews of the movie.
        /// </summary>
        public static string AmountReviews {
            get {
                return ResourceManager.GetString("AmountReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of users who like movie.
        /// </summary>
        public static string AmountUsers {
            get {
                return ResourceManager.GetString("AmountUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an action:.
        /// </summary>
        public static string ChooseAction {
            get {
                return ResourceManager.GetString("ChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of origin:.
        /// </summary>
        public static string CountryOfOrigin {
            get {
                return ResourceManager.GetString("CountryOfOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a movie.
        /// </summary>
        public static string CreateMovie {
            get {
                return ResourceManager.GetString("CreateMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the director.
        /// </summary>
        public static string DirectorName {
            get {
                return ResourceManager.GetString("DirectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a review.
        /// </summary>
        public static string LeaveReview {
            get {
                return ResourceManager.GetString("LeaveReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a review for the movie.
        /// </summary>
        public static string LeaveReviewForMovie {
            get {
                return ResourceManager.GetString("LeaveReviewForMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of movies:.
        /// </summary>
        public static string ListOfMovies {
            get {
                return ResourceManager.GetString("ListOfMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget of the movie:.
        /// </summary>
        public static string MovieBudget {
            get {
                return ResourceManager.GetString("MovieBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the movie:.
        /// </summary>
        public static string MovieDescription {
            get {
                return ResourceManager.GetString("MovieDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director of the movie:.
        /// </summary>
        public static string MovieDirector {
            get {
                return ResourceManager.GetString("MovieDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page of movie fan.
        /// </summary>
        public static string MovieFanPage {
            get {
                return ResourceManager.GetString("MovieFanPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the movie.
        /// </summary>
        public static string MovieName {
            get {
                return ResourceManager.GetString("MovieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate:.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release year:.
        /// </summary>
        public static string ReleaseYear {
            get {
                return ResourceManager.GetString("ReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to favorites.
        /// </summary>
        public static string ToFavorites_LowerCase {
            get {
                return ResourceManager.GetString("ToFavorites_LowerCase", resourceCulture);
            }
        }
    }
}
