//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalAboutEverything.LocalizationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Movie_CreateMovie {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Movie_CreateMovie() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalAboutEverything.LocalizationResources.Movie_CreateMovie", typeof(Movie_CreateMovie).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to budget.
        /// </summary>
        public static string Budget_LowerCase {
            get {
                return ResourceManager.GetString("Budget_LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of origin.
        /// </summary>
        public static string CountryOfOrigin_Display {
            get {
                return ResourceManager.GetString("CountryOfOrigin_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country of origin.
        /// </summary>
        public static string CountryOfOrigin_LowerCase {
            get {
                return ResourceManager.GetString("CountryOfOrigin_LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create.
        /// </summary>
        public static string Create_LowerCase {
            get {
                return ResourceManager.GetString("Create_LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string Description_LowerCase {
            get {
                return ResourceManager.GetString("Description_LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of director.
        /// </summary>
        public static string Director_Display {
            get {
                return ResourceManager.GetString("Director_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to director.
        /// </summary>
        public static string Director_LowerCase {
            get {
                return ResourceManager.GetString("Director_LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} contains incorrect symbols.
        /// </summary>
        public static string ForbiddenSymbols_ValidationErrorMessage {
            get {
                return ResourceManager.GetString("ForbiddenSymbols_ValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the movie should not be more then {0} symbols.
        /// </summary>
        public static string MovieDescription_ValidationErrorMessage {
            get {
                return ResourceManager.GetString("MovieDescription_ValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movie title.
        /// </summary>
        public static string MovieTitle_LowerCase {
            get {
                return ResourceManager.GetString("MovieTitle_LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release year.
        /// </summary>
        public static string ReleaseYear_Display {
            get {
                return ResourceManager.GetString("ReleaseYear_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to release year.
        /// </summary>
        public static string ReleaseYear_LowerCase {
            get {
                return ResourceManager.GetString("ReleaseYear_LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of origin is not filled in.
        /// </summary>
        public static string RequiredCountryOfOrigin_Error {
            get {
                return ResourceManager.GetString("RequiredCountryOfOrigin_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the director is not filled in.
        /// </summary>
        public static string RequiredNameDirector_Error {
            get {
                return ResourceManager.GetString("RequiredNameDirector_Error", resourceCulture);
            }
        }
    }
}
